layout_spectrum: 1
favicon: null
name: "William O'Ray"
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.9382979
  lightness: 1
  saturation: 0.819149
  rhythmicContrast: 0.3297872
  brandColors:
    - '#FEFFDF'
    - '#181416'
    - '#866933'
    - '#FFBC79'
    - '#D19148'
typography_spectrum: 0.12647
