name: "William O'Ray"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12647
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#18130f'
    - '#bcbbb9'
    - '#4b4744'
    - '#c1582c'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
